### ISSUE TITLE
英文標點也被譯...

### ISSUE THREAD

**Issue by v998** [softcup/New-Tongwentang-for-Chrome#6]
例如 `’` 會變成 `』`
@ https://blog.cloudflare.com/do-the-chacha-better-mobile-performance-with-cryptography/
設定：`自動轉為 繁體 (簡 > 繁)`

**Comment by softcup** [comment]
開啟「新同文堂」的「選項」，在「一般設定」->「標點符號轉換」切換成「停用 標點符號 轉換」即可避免這個問題發生。
